name: Run Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t tcp-connection-java .
      - name: Exec java program
        run: docker run --rm --name tcp-connection-java tcp-connection-java
